### ISSUE TITLE
denovo allele change

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#44]
DeNovo allele currently does not have a attribute stating that that the allele is/is not denovo.  The thought is that if you have a denovo allele element then you are saying that the allele is denovo.  This means we can't say that the allele is not denovo.  We might not need that, but I think it's better to be explicit, so I'd add an  isdenovo boolean.

**Comment by bpow** [comment]
Would this be better stated as an `AlleleInheritance` type? It could take a set of values:

* Maternally-inherited
* Paternally-inherited
* de novo
* unknown

We could also consider options like "non-maternal" and "non-paternal" when only one of the parents has been genotyped.

@srynobio : any thoughts on terms for this?

To some extent, this is a special case of `FamilySegregationData`, but I think it is used frequently enough to warrant specific modelling.

**Comment by larrybabb** [comment]
@cbizon @bpow Can you guys help finalize this at an upcoming meeting (or offline) and let me know? Is this gating our draft of the model?  

If we do need to separate out and code the type as @bpow suggests then can we add this to issue #56 with the other things like this.?

**Comment by cbizon** [comment]
I think Bradford's suggestion is the way to go.  I will add it to #56.

**Comment by rrfreimuth** [comment]
I concur with @bpow as well.  I like the addition of non-maternal and non-paternal, too.  One question:  when a trio is sequenced is there some determination made as to the likelihood of parentage prior to calling alleles "de novo"?  I'm wondering how many "de novo" need to be present before paternity is called into question, for example, at which point "non-maternal" may be more accurate.

**Comment by larrybabb** [comment]
I added Value Set #22 (AlleleInheritanceType) with the values per @bpow above. 

I will need someone to go through the "DeNovo" examples and identify the correct values for them.

@cbizon is this something you can do.  Feel free to do it in the original Google Doc of Criterion Examples and let me know. I can transfer them to the spreadsheet (if that is easier).

**Comment by larrybabb** [comment]
Waiting on @cbizon to update the [Criterion Examples google doc](DMWG - Criterion Assessment Examples) with the new values from the [Value Set for AlleleInheritanceType](http://datamodel.clinicalgenome.org/interpretation/master/tech/details/details.html#VS022).

**Comment by cbizon** [comment]
Done.  I simply added
`alleleInheritance: CG-allele-inheritance:denovo` to every DeNovo element that we had.

I do think that we need another value in the set for the case where mother & father are both heterozygous and the offspring is also heterozygous.  In this case it's sort of unknown, since it could have come from either.  "Unknown" sort of implies that it's completely unknown (i.e. could be de novo).  I guess in that case, it could be denovo, but I think we would normally say that was not.

Also the possibility of two homozygous parents, and the kid is homozygous with the same alleles as the parents.  Then its both maternal/paternal, but you don't know which is which.

**Comment by bpow** [comment]
The last statement about when a child is heterozygous and both parents are also heterozygous is true at the level of genotyping of that site without additional information, but doesn't preclude the possibility of determining that the allele was maternally inherited or paternally inherited (e.g., through linkage to a close site) or that there could actually be a functional difference between from whom the allele was inherited (in the case of imprinted regions).

I'm not advocating for complicating the model to represent this somehow, just pointing out that there is an edge case here.

**Comment by rrfreimuth** [comment]
Another edge case, although I don't think we need to worry about modeling it at this point:  how do we indicate that a variant has paternal origins when paternity is not as expected?

**Comment by larrybabb** [comment]
@cbizon I added CG-allele-inheritance:denovo to every DenovoAllele object in our examples. Not every one in the CriterionExamples was annotated with this, but I figured you missed some.  Please let me know if my assumption was incorrect if not you can close this issue.

**Comment by cbizon** [comment]
Oops sorry for doing an incomplete job. You were correct that they all needed that attribute and value so I am closing.
